// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddExternalFileToLibrary(arg1, arg2) {
  return window['go']['desktop']['App']['AddExternalFileToLibrary'](arg1, arg2);
}

export function AddSpellAllowlistWord(arg1) {
  return window['go']['desktop']['App']['AddSpellAllowlistWord'](arg1);
}

export function BrowserOpenURL(arg1) {
  return window['go']['desktop']['App']['BrowserOpenURL'](arg1);
}

export function ChangeLibraryLocation() {
  return window['go']['desktop']['App']['ChangeLibraryLocation']();
}

export function CodeActions(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['CodeActions'](arg1, arg2, arg3, arg4);
}

export function CommitPaths(arg1, arg2) {
  return window['go']['desktop']['App']['CommitPaths'](arg1, arg2);
}

export function Completion(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['Completion'](arg1, arg2, arg3);
}

export function CreateLibraryFile(arg1, arg2) {
  return window['go']['desktop']['App']['CreateLibraryFile'](arg1, arg2);
}

export function CreateLibraryFolder(arg1) {
  return window['go']['desktop']['App']['CreateLibraryFolder'](arg1);
}

export function DeleteLibraryFile(arg1) {
  return window['go']['desktop']['App']['DeleteLibraryFile'](arg1);
}

export function Diagnostics(arg1) {
  return window['go']['desktop']['App']['Diagnostics'](arg1);
}

export function DiscardPaths(arg1) {
  return window['go']['desktop']['App']['DiscardPaths'](arg1);
}

export function DocumentSymbols(arg1) {
  return window['go']['desktop']['App']['DocumentSymbols'](arg1);
}

export function GetCommands() {
  return window['go']['desktop']['App']['GetCommands']();
}

export function GetCurrentLibrary() {
  return window['go']['desktop']['App']['GetCurrentLibrary']();
}

export function GetFileGitStatus(arg1) {
  return window['go']['desktop']['App']['GetFileGitStatus'](arg1);
}

export function GetHiddenRevisions() {
  return window['go']['desktop']['App']['GetHiddenRevisions']();
}

export function GetLastActiveFile() {
  return window['go']['desktop']['App']['GetLastActiveFile']();
}

export function GetLibraryDirty() {
  return window['go']['desktop']['App']['GetLibraryDirty']();
}

export function GetLibraryTree() {
  return window['go']['desktop']['App']['GetLibraryTree']();
}

export function GetPreferences() {
  return window['go']['desktop']['App']['GetPreferences']();
}

export function GetRevisions(arg1, arg2) {
  return window['go']['desktop']['App']['GetRevisions'](arg1, arg2);
}

export function GetSpellAllowlist() {
  return window['go']['desktop']['App']['GetSpellAllowlist']();
}

export function GetWindowState() {
  return window['go']['desktop']['App']['GetWindowState']();
}

export function HideRevision(arg1) {
  return window['go']['desktop']['App']['HideRevision'](arg1);
}

export function MoveLibraryEntry(arg1, arg2) {
  return window['go']['desktop']['App']['MoveLibraryEntry'](arg1, arg2);
}

export function OpenExternalFileDialog() {
  return window['go']['desktop']['App']['OpenExternalFileDialog']();
}

export function Parse(arg1) {
  return window['go']['desktop']['App']['Parse'](arg1);
}

export function Quit() {
  return window['go']['desktop']['App']['Quit']();
}

export function ReadExternalFile(arg1) {
  return window['go']['desktop']['App']['ReadExternalFile'](arg1);
}

export function ReadFileAtRevision(arg1, arg2) {
  return window['go']['desktop']['App']['ReadFileAtRevision'](arg1, arg2);
}

export function ReadLibraryFile(arg1) {
  return window['go']['desktop']['App']['ReadLibraryFile'](arg1);
}

export function RemoveSpellAllowlistWord(arg1) {
  return window['go']['desktop']['App']['RemoveSpellAllowlistWord'](arg1);
}

export function RenameLibraryEntry(arg1, arg2) {
  return window['go']['desktop']['App']['RenameLibraryEntry'](arg1, arg2);
}

export function RenderHTML(arg1, arg2) {
  return window['go']['desktop']['App']['RenderHTML'](arg1, arg2);
}

export function RenderPDF(arg1, arg2) {
  return window['go']['desktop']['App']['RenderPDF'](arg1, arg2);
}

export function RestoreLibraryFile(arg1) {
  return window['go']['desktop']['App']['RestoreLibraryFile'](arg1);
}

export function RevealLibraryInExplorer() {
  return window['go']['desktop']['App']['RevealLibraryInExplorer']();
}

export function SaveFile(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['SaveFile'](arg1, arg2, arg3, arg4);
}

export function SaveWindowBounds(arg1, arg2) {
  return window['go']['desktop']['App']['SaveWindowBounds'](arg1, arg2);
}

export function SaveWindowBoundsIfNormal() {
  return window['go']['desktop']['App']['SaveWindowBoundsIfNormal']();
}

export function SemanticTokens(arg1) {
  return window['go']['desktop']['App']['SemanticTokens'](arg1);
}

export function SetActiveLibraryFile(arg1) {
  return window['go']['desktop']['App']['SetActiveLibraryFile'](arg1);
}

export function SetDisabledCommands(arg1) {
  return window['go']['desktop']['App']['SetDisabledCommands'](arg1);
}

export function SetInitialMenu(arg1) {
  return window['go']['desktop']['App']['SetInitialMenu'](arg1);
}

export function SetPreferences(arg1) {
  return window['go']['desktop']['App']['SetPreferences'](arg1);
}

export function ShowAboutDialog() {
  return window['go']['desktop']['App']['ShowAboutDialog']();
}

export function SnapshotFile(arg1, arg2) {
  return window['go']['desktop']['App']['SnapshotFile'](arg1, arg2);
}

export function SpellcheckContext(arg1) {
  return window['go']['desktop']['App']['SpellcheckContext'](arg1);
}

export function Stats(arg1) {
  return window['go']['desktop']['App']['Stats'](arg1);
}

export function TokenTypeNames() {
  return window['go']['desktop']['App']['TokenTypeNames']();
}

export function UnhideRevision(arg1) {
  return window['go']['desktop']['App']['UnhideRevision'](arg1);
}

export function UpgradeV1(arg1) {
  return window['go']['desktop']['App']['UpgradeV1'](arg1);
}

export function WriteLibraryFile(arg1, arg2) {
  return window['go']['desktop']['App']['WriteLibraryFile'](arg1, arg2);
}
