// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {protocol} from '../models';
import {menu} from '../models';
import {stats} from '../models';

export function AddExternalFileToLibrary(arg1:string,arg2:string):Promise<string>;

export function AddSpellAllowlistWord(arg1:string):Promise<boolean>;

export function BrowserOpenURL(arg1:string):Promise<void>;

export function ChangeLibraryLocation():Promise<string>;

export function CodeActions(arg1:string,arg2:number,arg3:number,arg4:Array<string>):Promise<desktop.codeActionsResultJSON>;

export function CommitPaths(arg1:Array<string>,arg2:string):Promise<void>;

export function Completion(arg1:string,arg2:number,arg3:number):Promise<protocol.CompletionList>;

export function CreateLibraryFile(arg1:string,arg2:string):Promise<string>;

export function CreateLibraryFolder(arg1:string):Promise<void>;

export function DeleteLibraryFile(arg1:string):Promise<void>;

export function Diagnostics(arg1:string):Promise<Array<desktop.diagnosticJSON>>;

export function DiscardPaths(arg1:Array<string>):Promise<void>;

export function DocumentSymbols(arg1:string):Promise<desktop.documentSymbolsResultJSON>;

export function GetCommands():Promise<Array<desktop.CommandMeta>>;

export function GetCurrentLibrary():Promise<string>;

export function GetFileGitStatus(arg1:string):Promise<desktop.FileGitStatus>;

export function GetHiddenRevisions():Promise<Array<string>>;

export function GetLastActiveFile():Promise<string>;

export function GetLibraryDirty():Promise<desktop.LibraryDirty>;

export function GetLibraryTree():Promise<Array<desktop.LibraryNode>>;

export function GetPreferences():Promise<desktop.Preferences>;

export function GetRevisions(arg1:string,arg2:number):Promise<Array<desktop.Revision>>;

export function GetSpellAllowlist():Promise<Array<string>>;

export function GetWindowState():Promise<desktop.WindowState>;

export function HideRevision(arg1:string):Promise<void>;

export function MoveLibraryEntry(arg1:string,arg2:string):Promise<string>;

export function OpenExternalFileDialog():Promise<string>;

export function Parse(arg1:string):Promise<Array<desktop.parseErrorJSON>>;

export function Quit():Promise<void>;

export function ReadExternalFile(arg1:string):Promise<desktop.ExternalFileResult>;

export function ReadFileAtRevision(arg1:string,arg2:string):Promise<string>;

export function ReadLibraryFile(arg1:string):Promise<string>;

export function RemoveSpellAllowlistWord(arg1:string):Promise<boolean>;

export function RenameLibraryEntry(arg1:string,arg2:string):Promise<string>;

export function RenderHTML(arg1:string,arg2:string):Promise<string>;

export function RenderPDF(arg1:string,arg2:desktop.PdfExportOptions):Promise<string>;

export function RestoreLibraryFile(arg1:string):Promise<void>;

export function RevealLibraryInExplorer():Promise<void>;

export function SaveFile(arg1:string,arg2:string,arg3:boolean,arg4:Array<desktop.FileFilter>):Promise<void>;

export function SaveWindowBounds(arg1:number,arg2:number):Promise<void>;

export function SaveWindowBoundsIfNormal():Promise<void>;

export function SemanticTokens(arg1:string):Promise<Array<number>>;

export function SetActiveLibraryFile(arg1:string):Promise<void>;

export function SetDisabledCommands(arg1:Array<string>):Promise<void>;

export function SetInitialMenu(arg1:menu.Menu):Promise<void>;

export function SetPreferences(arg1:desktop.Preferences):Promise<void>;

export function ShowAboutDialog():Promise<void>;

export function SnapshotFile(arg1:string,arg2:string):Promise<void>;

export function SpellcheckContext(arg1:string):Promise<desktop.spellcheckContextJSON>;

export function Stats(arg1:string):Promise<stats.Stats>;

export function TokenTypeNames():Promise<Array<string>>;

export function UnhideRevision(arg1:string):Promise<void>;

export function UpgradeV1(arg1:string):Promise<desktop.upgradeResultJSON>;

export function WriteLibraryFile(arg1:string,arg2:string):Promise<void>;
