version: 2

project_name: downstage

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: downstage
    binary: downstage
    main: ./
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/jscaltreto/downstage/cmd.version={{ .Version }}
      - -X github.com/jscaltreto/downstage/cmd.commit={{ .Commit }}
      - -X github.com/jscaltreto/downstage/cmd.date={{ .Date }}

archives:
  - id: default
    ids:
      - downstage
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - SPEC.md

checksum:
  name_template: checksums.txt

signs:
  - cmd: cosign
    artifacts: checksum
    output: true
    certificate: ${artifact}.pem
    args:
      - sign-blob
      - --yes
      - --output-certificate=${certificate}
      - --output-signature=${signature}
      - ${artifact}
    env:
      - COSIGN_YES=true

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github-native
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^style:"
